server:
  port: 8083
spring:
  application:
    name: gateway
  mvc:
    servlet:
      path: /api/v1
  eureka:
    client:
      serviceUrl:
        defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0